### ISSUE TITLE
provide an easy installer for this collection with "comtrya"

### ISSUE THREAD

**Issue by vielmetti** [vielmetti/vielmetti-shelltools#4]
Use something like @rawkode 's "comtrya" to automate the process of installing this collection, and by doing so also bring the collection up to date with actual current usage.

See https://github.com/rawkode/comtrya for that.

Reorganize this appropriately to match - there should be a `bin` and a `dotfiles` directory for files to separate them out.

**Comment by vielmetti** [comment]
also created a `manifest` directory to start collecting bits mostly of where to get the latest and greatest versions of things from private or ppa repos.

**Comment by vielmetti** [comment]
done: install with

`comtrya https://github.com/vielmetti/vielmetti-shelltools`

**Comment by rawkode** [comment]
The latest Comtrya (unreleased on main branch) this will become:

`comtrya apply https://github.com/vielmetti/vielmetti-shelltools`

Just FYI 😄
